/**
 * @mcp-tracker/shared
 *
 * Shared types and Prisma client exports for MCP Workflow Tracker.
 * This package is the source of truth for database types.
 */

// Re-export Prisma client, types, and enums
export {
  PrismaClient,
  // Types
  type Workflow,
  type Task,
  type Decision,
  type Issue,
  type Milestone,
  type Prisma,
  // Enums (generated by Prisma from schema)
  WorkflowStatus,
  TaskStatus,
  DecisionCategory,
  IssueType,
  TestsStatus,
} from '@prisma/client'
